### ISSUE TITLE
Add a Readme file

### ISSUE THREAD

**Issue by Dev-Ahmadubah** [PB2204/JS-DSA#3]
I noticed that this repository currently lacks a README file. A README file is essential for providing users and potential contributors with information about the project, how to use it, and how to contribute effectively. 

 I propose that we add a README file to this repository. I'd be willing to help with its creation.

**Note:**
Please assign this issue to me if you agree, or let me know how I can assist in creating the README.

**Comment by PB2204** [comment]
Currently I'm working on the documentation part of the project . I'll update the README.md file shortly . And then if you want to change anything , you can create a new issue or can make a PR . I'll merge this , if I find it helpful for the users . Thank you . Have a nice day !!!

**Comment by PB2204** [comment]
@Dev-Ahmadubah I've just updated the README.md file of the project . Please take a look into that , and let me know , If you want to make any update there.
